id = "9D50F353-27B6-44FE-9EF4-2969F9533969"

[[policy]]
policy_type = "Platform"
fmspc = "self"

[policy.Platform]

[policy.Platform.TcbInfo]
pcesvn = { operation = "equal", reference = "self" }
sgxtcbcomponents = { operation = "array-equal", reference = "self" }
tdxtcbcomponents = { operation = "array-equal", reference = "self" }

[[policy]]
policy_type = "QE"

[policy.QE]

[policy.QE.QeIdentity]
MISCSELECT = { operation = "equal", reference = "self" }
MRSIGNER = { operation = "equal", reference = "self" }
ISVPRODID = { operation = "equal", reference = "self" }
ISVSVN = { operation = "greater-or-equal", reference = "self" }
ATTRIBUTES = { operation = "equal", reference = "self" }

[[policy]]
policy_type = "TdxModule"

[policy.TDXModule]

[policy.TDXModule.TDXModule_Identity]
TDXModuleMajorVersion = { operation = "equal", reference = "self" }
TDXModuleSVN = { operation = "greater-or-equal", reference = "self" }
MRSIGNERSEAM = { operation = "equal", reference = "self" }
ATTRIBUTES = { operation = "equal", reference = "self" }

[[policy]]
policy_type = "MigTD"

[policy.MigTD]

[policy.MigTD.TDINFO]
ATTRIBUTES = { operation = "equal", reference = "self" }
XFAM = { operation = "equal", reference = "self" }
MRTD = { operation = "equal", reference = "self" }
MRCONFIGID = { operation = "equal", reference = "self" }
MROWNER = { operation = "equal", reference = "self" }
MROWNERCONFIG = { operation = "equal", reference = "self" }
RTMR0 = { operation = "equal", reference = "self" }
RTMR1 = { operation = "equal", reference = "self" }
RTMR2 = { operation = "equal", reference = "self" }
RTMR3 = { operation = "equal", reference = "self" }

[policy.MigTD.EventLog]
"Digest.MigTdPolicy" = { operation = "equal", reference = "self" }
"Digest.MigTdSgxRootKey" = { operation = "equal", reference = "self" }

[collateral]
pck_crl_issuer_chain = """
-----BEGIN CERTIFICATE-----
MIICljCCAj2gAwIBAgIVAJVvXc29G+HpQEnJ1PQzzgFXC95UMAoGCCqGSM49BAMC
MGgxGjAYBgNVBAMMEUludGVsIFNHWCBSb290IENBMRowGAYDVQQKDBFJbnRlbCBD
b3Jwb3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQsw
CQYDVQQGEwJVUzAeFw0xODA1MjExMDUwMTBaFw0zMzA1MjExMDUwMTBaMHAxIjAg
BgNVBAMMGUludGVsIFNHWCBQQ0sgUGxhdGZvcm0gQ0ExGjAYBgNVBAoMEUludGVs
IENvcnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0Ex
CzAJBgNVBAYTAlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENSB/7t21lXSO
2Cuzpxw74eJB72EyDGgW5rXCtx2tVTLq6hKk6z+UiRZCnqR7psOvgqFeSxlmTlJl
eTmi2WYz3qOBuzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBS
BgNVHR8ESzBJMEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2Vy
dmljZXMuaW50ZWwuY29tL0ludGVsU0dYUm9vdENBLmRlcjAdBgNVHQ4EFgQUlW9d
zb0b4elAScnU9DPOAVcL3lQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYB
Af8CAQAwCgYIKoZIzj0EAwIDRwAwRAIgXsVki0w+i6VYGW3UF/22uaXe0YJDj1Ue
nA+TjD1ai5cCICYb1SAmD5xkfTVpvo4UoyiSYxrDWLmUR4CI9NKyfPN+
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICjzCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw
aDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv
cnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ
BgNVBAYTAlVTMB4XDTE4MDUyMTEwNDUxMFoXDTQ5MTIzMTIzNTk1OVowaDEaMBgG
A1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0
aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT
AlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj/iPWsCzaEKi7
1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB
uzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ
MEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50
ZWwuY29tL0ludGVsU0dYUm9vdENBLmRlcjAdBgNVHQ4EFgQUImUM1lqdNInzg7SV
Ur9QGzknBqwwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwCgYI
KoZIzj0EAwIDSQAwRgIhAOW/5QkR+S9CiSDcNoowLuPRLsWGf/Yi7GSX94BgwTwg
AiEA4J0lrHoMs+Xo5o/sX6O9QWxHRAvZUGOdRQ7cvqRXaqI=
-----END CERTIFICATE-----
"""

root_ca_crl = """
-----BEGIN X509 CRL-----
MIIBIDCByAIBATAKBggqhkjOPQQDAjBoMRowGAYDVQQDDBFJbnRlbCBTR1ggUm9v
dCBDQTEaMBgGA1UECgwRSW50ZWwgQ29ycG9yYXRpb24xFDASBgNVBAcMC1NhbnRh
IENsYXJhMQswCQYDVQQIDAJDQTELMAkGA1UEBhMCVVMXDTI1MDMyMDExMjE1N1oX
DTI2MDQwMzExMjE1N1qgLzAtMAoGA1UdFAQDAgEBMB8GA1UdIwQYMBaAFCJlDNZa
nTSJ84O0lVK/UBs5JwasMAoGCCqGSM49BAMCA0cAMEQCIDDJ/OFDjaCpTk//3UbJ
ZQ45O+blp4YtTk5zUnky0ErzAiBlOe/j9zTD198g2d/EYw4cf/BDmg+OzhAfFbXq
/5tPMw==
-----END X509 CRL-----
"""

pck_crl = """
-----BEGIN X509 CRL-----
MIIKYjCCCggCAQEwCgYIKoZIzj0EAwIwcDEiMCAGA1UEAwwZSW50ZWwgU0dYIFBD
SyBQbGF0Zm9ybSBDQTEaMBgGA1UECgwRSW50ZWwgQ29ycG9yYXRpb24xFDASBgNV
BAcMC1NhbnRhIENsYXJhMQswCQYDVQQIDAJDQTELMAkGA1UEBhMCVVMXDTI1MDYy
NTE2MzYyM1oXDTI1MDcyNTE2MzYyM1owggk0MDMCFG/DTlAj5yiSNDXWGqS4PGGB
Zq01Fw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAO+ubpcV/KE7h+Mz
6CYe1tmQqSatFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAP1ghkhi
nLpzB4tNSS9LPqdBrQjNFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIV
AIr5JBhOHVr93XPD1joS9ei1c35WFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMK
AQEwNAIVALEleXjPqczdB1mr+MXKcvrjp4qbFw0yNTA2MjUxNjM2MjNaMAwwCgYD
VR0VBAMKAQEwMwIUdP6mFKlyvg4oQ/IFmDWBHthy+bMXDTI1MDYyNTE2MzYyM1ow
DDAKBgNVHRUEAwoBATA0AhUA+cTvVrOrSNV34Qi67fS/iAFCFLkXDTI1MDYyNTE2
MzYyM1owDDAKBgNVHRUEAwoBATAzAhQHHeB3j55fxPKHjzDWsHyaMOazCxcNMjUw
NjI1MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDQCFQDN4kJPlyzqlP8jmTf02AwlAp3W
CxcNMjUwNjI1MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDMCFGwzGeUQm2RQfTzxEyzg
A0nvUnMZFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAN8I11a2anSX
9DtbtYraBNP096k3Fw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwMwIUKK9I
W2z2fkCaOdXLWu5FmPeo+nsXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATA0
AhUA+4strsCSytqKqbxP8vHCDQNGZowXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUE
AwoBATA0AhUAzUhQrFK9zGmmpvBYyLxXu9C1+GQXDTI1MDYyNTE2MzYyM1owDDAK
BgNVHRUEAwoBATA0AhUAmU3TZm9SdfuAX5XdAr1QyyZ52K0XDTI1MDYyNTE2MzYy
M1owDDAKBgNVHRUEAwoBATAzAhQHAhNpACUidNkDXu31RXRi+tDvTBcNMjUwNjI1
MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDMCFGHyv3Pjm04EqifYAb1z0kMZtb+AFw0y
NTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwMwIUOZK+hRuWkC7/OJWebC7/GwZR
pLUXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATAzAhQP2kOgC2jqebfC3q6s
C0mL37KvkBcNMjUwNjI1MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDMCFGOfE5pQQP3P
8ZHopPsb8IbtYDlxFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAJWd
Uz+SSdweUTVEzcgwvxm38fMBFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEw
MwIUeuN3SKn5EvTGO6erB8WTzh0dEYEXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUE
AwoBATAzAhQTiEszJpk4wZWqFw/KddoXdTjfCxcNMjUwNjI1MTYzNjIzWjAMMAoG
A1UdFQQDCgEBMDQCFQCF08k4G3en4E0RnJ5a1nSf8/+rhxcNMjUwNjI1MTYzNjIz
WjAMMAoGA1UdFQQDCgEBMDQCFQCTiHykQR56kjvR/tKBmylJ8gG1tBcNMjUwNjI1
MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDMCFCSY3GKDkwmW/YvyOjesviajvtRXFw0y
NTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAIpm8adJSIZnaJzDkDrFTGYr
cS5zFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAK/BNhC902y3mF0Q
ZIGogNOgH9oHFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIVAO/gSywz
0DaqyWymc78emke2TVy7Fw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwNAIV
AIPZrI2LtQnRxsgJrXEuhDBVntfzFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMK
AQEwMwIUeTH9ULUHHBu/xbe23ti0W52LhSkXDTI1MDYyNTE2MzYyM1owDDAKBgNV
HRUEAwoBATAzAhQfog4pcL3l1X97jd+DOUhOHx0IIxcNMjUwNjI1MTYzNjIzWjAM
MAoGA1UdFQQDCgEBMDMCFB6HssOzLY0j5BHO80GXuVrwyK31Fw0yNTA2MjUxNjM2
MjNaMAwwCgYDVR0VBAMKAQEwNAIVAJr9LukKRzVQoWfZlpEUN8dQLR8JFw0yNTA2
MjUxNjM2MjNaMAwwCgYDVR0VBAMKAQEwMwIURIGw8RcooTtpbT6px3CgsV7FjdoX
DTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATA0AhUAp4WfV5gu8OZ9N7yO8u9a
yDX/GqkXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATA0AhUAnWd1O4HkcJCu
p2P77ExFSbzbmTMXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATAzAhQ0v7t6
HZxWgUfhGLYU97du0+9o3xcNMjUwNjI1MTYzNjIzWjAMMAoGA1UdFQQDCgEBMDMC
FCw8xv6SedsVFtXOOfKomM2loXXhFw0yNTA2MjUxNjM2MjNaMAwwCgYDVR0VBAMK
AQEwMwIUcXlIaHUJI0vpeeS33ObzG+9ktowXDTI1MDYyNTE2MzYyM1owDDAKBgNV
HRUEAwoBATA0AhUAnXbvLDnBNuhli25zlrHXRFonYx8XDTI1MDYyNTE2MzYyM1ow
DDAKBgNVHRUEAwoBATA0AhUAw+Al/KmV829ZtIRnk54+NOY2Gm8XDTI1MDYyNTE2
MzYyM1owDDAKBgNVHRUEAwoBATA0AhUAjF9rMlfaBbF0KeLmG6ll1nMwYGoXDTI1
MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBATA0AhUAoXxRci7B4MMnj+i98FIFnL7E
5kgXDTI1MDYyNTE2MzYyM1owDDAKBgNVHRUEAwoBAaAvMC0wCgYDVR0UBAMCAQEw
HwYDVR0jBBgwFoAUlW9dzb0b4elAScnU9DPOAVcL3lQwCgYIKoZIzj0EAwIDSAAw
RQIhALiSuFKkBQ7istFYkK+xiTORyaQHKaFNORqwUHTv7x5AAiAaufWCb95COBZO
YtxN6FgnVn9FcOIMhFGi0/8UbjIYFw==
-----END X509 CRL-----
"""

tcb_info_issuer_chain = """
-----BEGIN CERTIFICATE-----
MIICjTCCAjKgAwIBAgIUfjiC1ftVKUpASY5FhAPpFJG99FUwCgYIKoZIzj0EAwIw
aDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv
cnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ
BgNVBAYTAlVTMB4XDTI1MDUwNjA5MjUwMFoXDTMyMDUwNjA5MjUwMFowbDEeMBwG
A1UEAwwVSW50ZWwgU0dYIFRDQiBTaWduaW5nMRowGAYDVQQKDBFJbnRlbCBDb3Jw
b3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQswCQYD
VQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABENFG8xzydWRfK92bmGv
P+mAh91PEyV7Jh6FGJd5ndE9aBH7R3E4A7ubrlh/zN3C4xvpoouGlirMba+W2lju
ypajgbUwgbIwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqwwUgYDVR0f
BEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNlcnZpY2Vz
LmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5kZXIwHQYDVR0OBBYEFH44gtX7VSlK
QEmORYQD6RSRvfRVMA4GA1UdDwEB/wQEAwIGwDAMBgNVHRMBAf8EAjAAMAoGCCqG
SM49BAMCA0kAMEYCIQDdmmRuAo3qCO8TC1IoJMITAoOEw4dlgEBHzSz1TuMSTAIh
AKVTqOkt59+co0O3m3hC+v5Fb00FjYWcgeu3EijOULo5
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICjzCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw
aDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv
cnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ
BgNVBAYTAlVTMB4XDTE4MDUyMTEwNDUxMFoXDTQ5MTIzMTIzNTk1OVowaDEaMBgG
A1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0
aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT
AlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj/iPWsCzaEKi7
1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB
uzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ
MEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50
ZWwuY29tL0ludGVsU0dYUm9vdENBLmRlcjAdBgNVHQ4EFgQUImUM1lqdNInzg7SV
Ur9QGzknBqwwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwCgYI
KoZIzj0EAwIDSQAwRgIhAOW/5QkR+S9CiSDcNoowLuPRLsWGf/Yi7GSX94BgwTwg
AiEA4J0lrHoMs+Xo5o/sX6O9QWxHRAvZUGOdRQ7cvqRXaqI=
-----END CERTIFICATE-----
"""

tcb_info = """
{"tcbInfo":{"id":"TDX","version":3,"issueDate":"2025-06-25T16:04:55Z","nextUpdate":"2025-07-25T16:04:55Z","fmspc":"90C06F000000","pceId":"0000","tcbType":0,"tcbEvaluationDataNumber":17,"tdxModule":{"mrsigner":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","attributes":"0000000000000000","attributesMask":"FFFFFFFFFFFFFFFF"},"tdxModuleIdentities":[{"id":"TDX_03","mrsigner":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","attributes":"0000000000000000","attributesMask":"FFFFFFFFFFFFFFFF","tcbLevels":[{"tcb":{"isvsvn":3},"tcbDate":"2024-03-13T00:00:00Z","tcbStatus":"UpToDate"}]},{"id":"TDX_01","mrsigner":"000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","attributes":"0000000000000000","attributesMask":"FFFFFFFFFFFFFFFF","tcbLevels":[{"tcb":{"isvsvn":4},"tcbDate":"2024-03-13T00:00:00Z","tcbStatus":"UpToDate"},{"tcb":{"isvsvn":2},"tcbDate":"2023-08-09T00:00:00Z","tcbStatus":"OutOfDate"}]}],"tcbLevels":[{"tcb":{"sgxtcbcomponents":[{"svn":2,"category":"BIOS","type":"Early Microcode Update"},{"svn":2,"category":"OS/VMM","type":"SGX Late Microcode Update"},{"svn":2,"category":"OS/VMM","type":"TXT SINIT"},{"svn":2,"category":"BIOS"},{"svn":3,"category":"BIOS"},{"svn":1,"category":"BIOS"},{"svn":0},{"svn":5,"category":"OS/VMM","type":"SEAMLDR ACM"},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0}],"pcesvn":13,"tdxtcbcomponents":[{"svn":5,"category":"OS/VMM","type":"TDX Module"},{"svn":0,"category":"OS/VMM","type":"TDX Module"},{"svn":2,"category":"OS/VMM","type":"TDX Late Microcode Update"},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0}]},"tcbDate":"2024-03-13T00:00:00Z","tcbStatus":"UpToDate"},{"tcb":{"sgxtcbcomponents":[{"svn":2,"category":"BIOS","type":"Early Microcode Update"},{"svn":2,"category":"OS/VMM","type":"SGX Late Microcode Update"},{"svn":2,"category":"OS/VMM","type":"TXT SINIT"},{"svn":2,"category":"BIOS"},{"svn":3,"category":"BIOS"},{"svn":1,"category":"BIOS"},{"svn":0},{"svn":5,"category":"OS/VMM","type":"SEAMLDR ACM"},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0}],"pcesvn":5,"tdxtcbcomponents":[{"svn":5,"category":"OS/VMM","type":"TDX Module"},{"svn":0,"category":"OS/VMM","type":"TDX Module"},{"svn":2,"category":"OS/VMM","type":"TDX Late Microcode Update"},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0},{"svn":0}]},"tcbDate":"2018-01-04T00:00:00Z","tcbStatus":"OutOfDate","advisoryIDs":["INTEL-SA-00106","INTEL-SA-00115","INTEL-SA-00135","INTEL-SA-00203","INTEL-SA-00220","INTEL-SA-00233","INTEL-SA-00270","INTEL-SA-00293","INTEL-SA-00320","INTEL-SA-00329","INTEL-SA-00381","INTEL-SA-00389","INTEL-SA-00477","INTEL-SA-00837"]}]},"signature":"366bd4777121a9235a423f63e72a0f7b21a1954c2afd5c1aacbf1ee7dc23f13487484e089bd54d217675148ca3a8ecab167886dec01976ed1b1611ca57fb8c5f"}
"""

qe_identity_issuer_chain = """
-----BEGIN CERTIFICATE-----
MIICjTCCAjKgAwIBAgIUfjiC1ftVKUpASY5FhAPpFJG99FUwCgYIKoZIzj0EAwIw
aDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv
cnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ
BgNVBAYTAlVTMB4XDTI1MDUwNjA5MjUwMFoXDTMyMDUwNjA5MjUwMFowbDEeMBwG
A1UEAwwVSW50ZWwgU0dYIFRDQiBTaWduaW5nMRowGAYDVQQKDBFJbnRlbCBDb3Jw
b3JhdGlvbjEUMBIGA1UEBwwLU2FudGEgQ2xhcmExCzAJBgNVBAgMAkNBMQswCQYD
VQQGEwJVUzBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABENFG8xzydWRfK92bmGv
P+mAh91PEyV7Jh6FGJd5ndE9aBH7R3E4A7ubrlh/zN3C4xvpoouGlirMba+W2lju
ypajgbUwgbIwHwYDVR0jBBgwFoAUImUM1lqdNInzg7SVUr9QGzknBqwwUgYDVR0f
BEswSTBHoEWgQ4ZBaHR0cHM6Ly9jZXJ0aWZpY2F0ZXMudHJ1c3RlZHNlcnZpY2Vz
LmludGVsLmNvbS9JbnRlbFNHWFJvb3RDQS5kZXIwHQYDVR0OBBYEFH44gtX7VSlK
QEmORYQD6RSRvfRVMA4GA1UdDwEB/wQEAwIGwDAMBgNVHRMBAf8EAjAAMAoGCCqG
SM49BAMCA0kAMEYCIQDdmmRuAo3qCO8TC1IoJMITAoOEw4dlgEBHzSz1TuMSTAIh
AKVTqOkt59+co0O3m3hC+v5Fb00FjYWcgeu3EijOULo5
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIICjzCCAjSgAwIBAgIUImUM1lqdNInzg7SVUr9QGzknBqwwCgYIKoZIzj0EAwIw
aDEaMBgGA1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENv
cnBvcmF0aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJ
BgNVBAYTAlVTMB4XDTE4MDUyMTEwNDUxMFoXDTQ5MTIzMTIzNTk1OVowaDEaMBgG
A1UEAwwRSW50ZWwgU0dYIFJvb3QgQ0ExGjAYBgNVBAoMEUludGVsIENvcnBvcmF0
aW9uMRQwEgYDVQQHDAtTYW50YSBDbGFyYTELMAkGA1UECAwCQ0ExCzAJBgNVBAYT
AlVTMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEC6nEwMDIYZOj/iPWsCzaEKi7
1OiOSLRFhWGjbnBVJfVnkY4u3IjkDYYL0MxO4mqsyYjlBalTVYxFP2sJBK5zlKOB
uzCBuDAfBgNVHSMEGDAWgBQiZQzWWp00ifODtJVSv1AbOScGrDBSBgNVHR8ESzBJ
MEegRaBDhkFodHRwczovL2NlcnRpZmljYXRlcy50cnVzdGVkc2VydmljZXMuaW50
ZWwuY29tL0ludGVsU0dYUm9vdENBLmRlcjAdBgNVHQ4EFgQUImUM1lqdNInzg7SV
Ur9QGzknBqwwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwCgYI
KoZIzj0EAwIDSQAwRgIhAOW/5QkR+S9CiSDcNoowLuPRLsWGf/Yi7GSX94BgwTwg
AiEA4J0lrHoMs+Xo5o/sX6O9QWxHRAvZUGOdRQ7cvqRXaqI=
-----END CERTIFICATE-----
"""

qe_identity = """
{"enclaveIdentity":{"id":"TD_QE","version":2,"issueDate":"2025-06-25T16:55:12Z","nextUpdate":"2025-07-25T16:55:12Z","tcbEvaluationDataNumber":17,"miscselect":"00000000","miscselectMask":"FFFFFFFF","attributes":"11000000000000000000000000000000","attributesMask":"FBFFFFFFFFFFFFFF0000000000000000","mrsigner":"DC9E2A7C6F948F17474E34A7FC43ED030F7C1563F1BABDDF6340C82E0E54A8C5","isvprodid":2,"tcbLevels":[{"tcb":{"isvsvn":4},"tcbDate":"2024-03-13T00:00:00Z","tcbStatus":"UpToDate"}]},"signature":"3e4dfbd8c83265ca69861f729a543bc1d8447b362555bba534141daacbb75bb4a4776dba7f51db7f9797d8af35616e3eef33834b063046d364bb69d271d1a781"}
"""