[package]
name = "tcp_transport"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["rt", "net", "io-util", "macros"], optional = true }
async_io = { path = "../../async/async_io" }

[features]
std = []
AzCVMEmu = ["std", "tokio"]
